name = "nabhani"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "185.81.29.187:443"
UUID = "51a67045-820c-4ec2-8807-f1dc3078eaa6"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
